<#
.SYNOPSIS
    Build this Volt app for WebAssembly on Windows.
    Generated by create-volt-app.ps1

.DESCRIPTION
    Mirrors build.sh but runs natively on Windows PowerShell.
    Requires Emscripten (emcc) in PATH.
    Tip: run   . <path-to-emsdk>\emsdk_env.ps1   first.

.PARAMETER Guid
    VOLT_GUID for this app (default: APP_GUID_PLACEHOLDER)
#>
param([string]$Guid = "APP_GUID_PLACEHOLDER")

$ErrorActionPreference = "Stop"
function Info { param($m) Write-Host "[INFO]  $m" -ForegroundColor Cyan }
function Ok   { param($m) Write-Host "[ OK ]  $m" -ForegroundColor Green }
function Fail { param($m) Write-Host "[ERR ]  $m" -ForegroundColor Red; exit 1 }

# Always run from the app directory regardless of where we were invoked from
Set-Location $PSScriptRoot

Write-Host ""
Write-Host "=================================================================" -ForegroundColor Cyan
Write-Host "  Volt Build  -  APP_NAME_PLACEHOLDER" -ForegroundColor Cyan
Write-Host "=================================================================" -ForegroundColor Cyan
Write-Host ""

# --- prereqs ----------------------------------------------------------------
if (-not (Get-Command emcc -ErrorAction SilentlyContinue)) {
    Fail "emcc not found. Source emsdk first:`n  . <emsdk_dir>\emsdk_env.ps1"
}

$python = if ($env:EMSDK_PYTHON) { $env:EMSDK_PYTHON } else { "python" }
Info "Using python : $python"
Info "GUID         : $Guid"
Write-Host ""

# --- preprocess .x. files ---------------------------------------------------
$GeneratedDir = Join-Path $PSScriptRoot "_generated"
if (Test-Path $GeneratedDir) { Remove-Item $GeneratedDir -Recurse -Force }
New-Item -ItemType Directory -Path "$GeneratedDir\src" -Force | Out-Null

Info "Preprocessing source files..."
Get-ChildItem -Path (Join-Path $PSScriptRoot "src") -Recurse -File | ForEach-Object {
    $rel  = $_.FullName.Substring(($PSScriptRoot + "\src\").Length)
    $dest = "$GeneratedDir\src\$rel"
    New-Item -ItemType Directory -Path (Split-Path $dest) -Force | Out-Null

    if ($_.Name -match '\.x\.') {
        Info "  preprocess: $rel"
        # Pass output path as 2nd arg - preprocessor writes UTF-8 directly
        # (avoids PowerShell stdout capture collapsing newlines / writing UTF-16)
        & $python preprocesor.py $_.FullName $dest
        if ($LASTEXITCODE -ne 0) { Fail "Preprocessor failed for $($rel)" }
    } else {
        Copy-Item $_.FullName $dest -Force
    }
}

$mainSrc = Join-Path $GeneratedDir "src\main.x.cpp"
if (-not (Test-Path $mainSrc)) { Fail "main.x.cpp not found in generated tree" }
Ok "Preprocessing done"

# --- compile ----------------------------------------------------------------
$outputDir = Join-Path $PSScriptRoot "output"
New-Item -ItemType Directory -Path $outputDir -Force | Out-Null

Info "Compiling to WebAssembly..."

# GUID quoting: PowerShell -> emcc.ps1 (Python) strips shell quotes.
# Solution: write a clang response file with backslash-escaped quotes.
# Clang reads response files directly, bypassing all shell quoting layers.
$responseFile = Join-Path $PSScriptRoot "_build_flags.rsp"
"-DVOLT_GUID=\`"$Guid\`"" | Set-Content $responseFile -Encoding ASCII -NoNewline

$emccArgs = @(
    $mainSrc,
    "@$responseFile",   # clang reads GUID flag directly from this file
    "-DDEBUG",
    "-DVOLT_ENABLE_LOG",
    "-I", (Join-Path $PSScriptRoot "dependencies\volt\include"),
    "-o", "$outputDir\app.js",
    "-lembind",
    "-std=c++20",
    "-s", "WASM=1",
    "-s", "ALLOW_MEMORY_GROWTH=1",
    "-s", "MODULARIZE=1",
    "-s", "EXPORT_NAME=VoltApp",
    "-s", 'EXPORTED_RUNTIME_METHODS=["ccall","cwrap"]',
    "--bind",
    "-O0",
    "-g"
)

& emcc @emccArgs
if ($LASTEXITCODE -ne 0) { Fail "emcc failed (exit $LASTEXITCODE)" }

# --- copy HTML / CSS --------------------------------------------------------
Copy-Item (Join-Path $PSScriptRoot "index.html") $outputDir -Force
Copy-Item (Join-Path $PSScriptRoot "global.css")  $outputDir -Force

Ok "Build complete!"
Write-Host ""
Info "Output files:"
Write-Host "   output\app.js"
Write-Host "   output\app.wasm"
Write-Host "   output\index.html"
Write-Host ""
Info "To run:"
Write-Host "   cd output"
Write-Host "   python -m http.server 8001"
Write-Host "   # open http://localhost:8001"
Write-Host ""
